# Site settings
title: Design-Led Research Toolkit
description: >
  Design-Led Research Toolkit

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://127.0.0.1:4000" 
url: "http://dlrtoolkit.github.io"

author:
  fullname: 
  googleplus: 
  github: 
  twitter:
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown