# Site settings
title: Design-led Research Toolkit
description: >
  Design-led Research Toolkit

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dlrtoolkit.github.io" # the base hostname & protocol for your site

author:
  fullname: 
  googleplus: 
  github: 
  twitter:
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown